### ISSUE TITLE
Is this still WIP?

### ISSUE THREAD

**Issue by thewebartisan7** [spatie/laravel-data-demo#1]
I was looking for some more advanced usage of laravel-data and I found this.

Are you still working on this demo? As I can see only one Data class.

In case I hope you can add some advanced usage, for example how to handle nested data object via request.

For example let's suppose that your PostData has many tags and many topics, and so that this is in PostData as DataCollection.

When data is coming from request, I see strange things happening.

Since I am sending only an array of topics IDs and tags with comma separated which I convert to explode to an array, I found this PostData object:

<img width="470" alt="Screenshot 2022-08-26 at 17 48 11" src="https://user-images.githubusercontent.com/57477934/186947626-8631d4d7-b038-42db-93f0-02a77bda1f91.png">

The second dump is request()->all()

As you can see the IDs are create in TopicData with name => id. How this happen not sure, because a nested object with fromRequest() seem not taken into account..

Below is my TopicData class.

```php
class TopicData extends Data
{
    public function __construct(
        public int|Optional $id,

        public string|Optional $name,

        public string|Optional $slug
    ) {
    }
}
```

```php
<?php
// Semplified PostData class
#[MapName(SnakeCaseMapper::class)]
class PostData extends Data
{
    public function __construct(
        #[Max(255)]
        public string $title,
        public string $body,

        #[DataCollectionOf(TopicData::class)]
        public DataCollection|Optional $topics,

        #[DataCollectionOf(TagData::class)]
        public DataCollection|Optional $tags,
        #[Date]
        public CarbonImmutable|Optional|null $publishedAt,
    ) {
    }
}
```

Then with data-transfert-object I could use ->only() and ->except(), but when using this with laravel-data, then ->all() doesn't return all values, I have to use $data->topics.

```php
$data->all(); // yes is all
$data->only('title'); // only title
$data->all(); // only title
```

My action code:

```php
    /**
     * @param PostData $data
     * @return Post
     */
    public function execute(PostData $data): Post
    {
        $post = Post::create(
            $data->except('topics', 'tags')->toArray()
        );

        $this->topicSyncAction->execute($post, $data->topics);
        $this->tagSyncAction->execute($post, $data->tags);

        return $post;
    }
```

Thank You!

**Comment by thewebartisan7** [comment]
I maybe sort out something with fromRequest():

```php
    public static function fromRequest(Request $request): self
    {
        return self::from([
            ...$request->all(),
            'tags' => TagData::collection(
                Tag::whereIn('id', $request->collect('tags'))->get()
            ),
            'topics' => TopicData::collection(
                Topic::whereIn('id', $request->collect('topics'))->get()
            ),
        ]);
    }
```

But still would be great to have some example from you.

**Comment by freekmurze** [comment]
This repo will be used in a demo application that I'll use during a talk. For questions, open a discussion at the laravel-data repo.
